### ISSUE TITLE
Doesn't work with GET querystrings

### ISSUE THREAD

**Issue by brianlaw033** [vigetlabs/olive_branch#20]
After spending some time debugging, I realise that it doesn't convert camelCase in a GET request, any way to achieve that?

**Comment by efatsi** [comment]
@brianlaw033 sorry for the lack of response. Could this be due to the content type check? See my latest comment on #23 - https://github.com/vigetlabs/olive_branch/issues/23#issuecomment-362340068

**Comment by wxgeorge** [comment]
I recently debugged the same problem (translation not happening on GET requests for lack of 'Content-Type' header).

In my case, my client library (Axios) drops 'Content-Type' header for requests that have no body (see, e.g., [here](https://github.com/axios/axios/issues/86)) which is the default for GET requests (see, e.g., [here](https://stackoverflow.com/questions/978061/http-get-with-request-body)).

I came to this OliveBranch project page looking for some input on how others have negotiated this issue (so thoughts welcome!), but I haven't seen that yet.

**Comment by efatsi** [comment]
@wxgeorge if there's a way to configure Axios to leave the header in that'd be nice (I don't know much about Axios). A change on this end might be a good solution as well though. What are your thoughts on an always-on configuration?

**Comment by wxgeorge** [comment]
@efatsi would an "always-on" configuration be different from a "content-type check disabled" configuration? The latter seems to be already supported.

**Comment by efatsi** [comment]
Yes indeed. Looks like you suggested something along those lines in your initial question. Going to close this out unless there's any further questions.

**Comment by wxgeorge** [comment]
@efatsi I've opened #29 to amend the README to try and reduce confusion for future developers.
