### ISSUE TITLE
Not working for requests sent in, only for responses sent back

### ISSUE THREAD

**Issue by zachfeldman** [vigetlabs/olive_branch#23]
Hey there, great idea for a library! If I send the header, I can get back camelCased keys, but if I send camelCased keys, they are not translated to snake-case. I am passing in the X-Key-Inflection header with a value of camel, along with camelcased keys.

I'm on Rails 5.0.6 and Ruby 2.4.2p198 . I've put this in my `application.rb`

`config.middleware.use OliveBranch::Middleware`

Any ideas @efatsi or others?

**Comment by efatsi** [comment]
Ahoy. By default this gem only transforms keys for requests with `application/json` content type, is that catching you up by chance? If yes, you can pass in a content type checking method like so:
```ruby
config.middleware.use OliveBranch::Middleware, content_type_check: -> (content_type) { content_type == "my/content-type" }
```
or even
```ruby
config.middleware.use OliveBranch::Middleware, content_type_check: -> (content_type) { true }
```
if you want it to run on every single request.

If that's not it, you should be able to `bundle open olive_branch`, throw some debugging statements in there, restart your local server and see what's causing the transformation to be bypassed.

Good luck!

**Comment by zachfeldman** [comment]
Thanks, this is extremely helpful! Now it's working as expected. Urock

**Comment by efatsi** [comment]
Good to hear. I'll add a note to the README, don't think this is the first time someone's hit this issue before.
