### ISSUE TITLE
Converting between camelCase and snake_case in-app

### ISSUE THREAD

**Issue by JamesPlayer** [vigetlabs/olive_branch#28]
The react app I'm working on gets its initial state via a json blob that is dumped onto the page like so:

```
<script>
  window.preloadedState = <%= raw @app_state.to_json %>
</script>
```

I'd like to use this library for json API calls but also to convert the initial state from snake case to camel case. It seems like the current implementation does not handle this use case. Is there any way to do this using Olive branch that I've missed?

**Comment by efatsi** [comment]
The gem itself doesn't have an explicit API from this, but peeking at the source (which is a bit roundabout at this point to handle the flexibility desired by various folks over the years), the actual transformation operation isn't too bad. Should be something like this:
```rb
@app_state.as_json.deep_transform_keys{|k| k.underscore.camelize(:lower) }
```

**Comment by JamesPlayer** [comment]
Ok thanks for the reply, closing.
