### ISSUE TITLE
Documenting a common use case?

### ISSUE THREAD

**Issue by pupeno** [vigetlabs/olive_branch#39]
It took me a while to understand how to use OliveBranch on my own project and I was very close to giving up with it. I ended up with this code:

```ruby
    excluded_routes = ->(env) { !env["PATH_INFO"].match(%r{^/api}) }
    config.middleware.use OliveBranch::Middleware,
                          inflection:         "camel",
                          exclude_params:     excluded_routes,
                          exclude_response:   excluded_routes,
                          content_type_check: ->(content_type) { content_type == "application/json" }
```

Essentially: modify params in and out, for the whole api, to have snake case inside and camel case outside. I think this is a common scenario. Would you like me to add it to the readme? I also wonder whether there should be a shorthand for that exactly.

**Comment by efatsi** [comment]
Thanks @pupeno. Sorry to hear the startup for this was such a challenge. I think this project has grown in customization possibilities over the years at the expense of a reasonable default. I think adding this to the readme would be a great idea. Would you care to spin up a PR for the project?

**Comment by pupeno** [comment]
Yup. Happy to do so.
